org.gradle.jvmargs = -Xmx2G --enable-native-access=ALL-UNNAMED
org.gradle.parallel = true

maven_group = io.github.iceecron
archives_base_name = carpet-ssl-addition

mod.id = carpet-ssl-addition
mod.name = carpet-ssl-addition
mod.version = 1.2.0
mod.description = Adds Carpet rules to adjust and fix certain Minecraft behaviors

dependencies.minecraft_version = 26.1.2
dependencies.minecraft_dependency = >26.0
dependencies.loader_version = 0.18.4
loom_version = 1.15-SNAPSHOT

org.gradle.java.home=C:/Program Files/Java/graalvm-jdk-25.0.2+10.1