org.gradle.jvmargs = -Xmx2G --enable-native-access=ALL-UNNAMED
org.gradle.parallel = true

maven_group = io.github.iceecron
archives_base_name = carpet-ssl-addition

mod.id = carpet-ssl-addition
mod.name = Carpet SSL Addition
mod.version = 2.1.0
mod.description = Carpet rules for End gateway landing and dolphin pickup behavior

dependencies.minecraft_version = 26.1.2
dependencies.minecraft_dependency = >26.0
dependencies.loader_version = 0.18.4
loom_version = 1.15-SNAPSHOT

org.gradle.java.home=C:/Program Files/Java/graalvm-jdk-25.0.2+10.1
